#!/usr/bin/env python3
"""Scheme E — the official design. Built page by page on scheme D's palette
and type (pure green + Fredoka + rounded shapes).

    python3 scheme_e.py         # write the SVG pages
    python3 scheme_e.py --gif   # also build the motion GIFs

Pages live in screenshots/scheme-e/.

Numbering follows the swipe axis, centred on Home:

    00w   welcome / splash — off-axis, shown once at cold launch
    0.5   add-a-bean form — off-axis, reached by tapping Add bean from Home
    0.51  the label-scanning camera, reached from 0.5's scan prompt;
          0.51b is what it becomes when camera permission is denied
    0.6   the saved bean profile — off-axis, tapping a bean on Home;
          0.6b is the same page scrolled past the fold
    -2    <- swipe left     -1    <- swipe left
    00    HOME
    +1    swipe right ->    +2    swipe right ->

+2 is the profile page, and it is the one screen that has a signed-out state:
+2_profile_empty is what you get before anyone has logged in, +2_profile once
they have. Home carries no avatar in either case — it used to sit in the top
bar, but an avatar is a signed-in artifact and 00_home_empty is by definition
a phone nobody has logged into yet, so profile lives on the swipe axis only.

A page's state is a suffix on the same number (00_home, 00_home_empty), since
states are the same destination, not a different one.
"""
from __future__ import annotations
import math, pathlib, random, sys, subprocess, tempfile

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import wireframes as wf
import variants as V

OUT = HERE / "screenshots" / "scheme-e"
W, H = wf.W, wf.H

# scheme D's tokens and type, adopted as scheme E's baseline
wf.C.update(V.PURE_GREEN)
wf.SEQ[:] = V.PURE_GREEN_SEQ
V._apply_style(V.FREDOKA_STYLE)

BRAND = wf.BRAND_MARK          # #34C759 — the logo's own green
wf.AVATAR = "R"

# Inline the typeface so a page looks the same in a browser, an IDE preview
# and the exported GIF — not just where Fredoka happens to be installed.
wf.EMBED["Fredoka"] = str(pathlib.Path.home() / ".local/share/fonts/Fredoka-var.ttf")

# Display face for the big headlines. Fredoka is the logo's own face, so the
# headline and the mark share letterforms. Chewy was evaluated for these
# moments and rejected: it is a third voice that does not match the logo, and
# it ships in one weight only.
FREDOKA = "Fredoka,'Liberation Sans',sans-serif"
CHEWY = "Chewy,Fredoka,'Liberation Sans',sans-serif"   # evaluated, not used
HEADLINE = FREDOKA

# dripper_icons/ (generated by dripper_icons/generate.py) is a standalone
# asset folder, not otherwise imported by this file -- read lazily so a page
# that never draws a dripper icon doesn't pay for fifteen file reads.
_DRIPPER_ICONS = HERE / "dripper_icons"
_DRIPPER_SLUG = {"V60": "hario-v60", "Kalita": "kalita-wave", "Chemex": "chemex"}
_dripper_icon_cache: dict[str, str] = {}


def dripper_icon(c, cx, cy, size, name):
    """A dripper's icon (generate.py's white-line figures, matching
    can_boy()/bag_tile()'s own recipe), scaled to fit inside a `size`-wide
    box centred on (cx, cy). Draws only the white linework -- the caller
    owns the backing shape/colour (a bag_tile()-style green chip, a circle,
    whatever the slot already is), the same division of responsibility
    bag_tile() itself doesn't need because it draws its own background.

    Returns False and draws nothing if `name` isn't one of the fifteen the
    icon set covers -- real dripper lists are user-editable
    (coffee_can.drippers), so an unmapped name is expected, not a bug; the
    caller should have a fallback (initials, plain text, ...) ready.
    """
    slug = _DRIPPER_SLUG.get(name)
    if slug is None:
        return False
    if slug not in _dripper_icon_cache:
        svg_text = (_DRIPPER_ICONS / f"{slug}.svg").read_text()
        _dripper_icon_cache[slug] = svg_text.split(">", 1)[1].rsplit("</svg>", 1)[0]
    s = size / 100
    c.add(f'<g transform="translate({cx-size/2:.1f} {cy-size/2:.1f}) scale({s:.4f})">'
          + _dripper_icon_cache[slug] + '</g>')
    return True


# ------------------------------------------------------------- 00 welcome ---
def welcome(fade: float = 1.0):
    """Cold-launch splash. The field is the logo's own green, so the disc is
    dropped — a #34C759 disc on a #34C759 ground is invisible. What remains is
    the wordmark knocked out in white, which is how the mark is meant to sit
    on its own colour.

    `fade` drives the 1s ease-out reveal; 1.0 is the resting state.
    """
    c = wf.Canvas("Welcome — scheme E", bg=BRAND)
    # Dark status-bar ink: light-content icons would be 2.22:1 on this green.
    # #002602 is onPrimaryContainer and measures 7.40:1.
    n = len(c.body)
    wf.status_bar(c)
    c.body[n:] = [b.replace(wf.C["onSurfaceVariant"], "#002602") for b in c.body[n:]]

    c.add(f'<g opacity="{fade:.4f}">')
    wf.logo(c, W / 2, H / 2 - 4, 290, tagline=True, disc=False)
    c.add("</g>")
    return c


# --------------------------------------------------------------- bag tile --
def bag_tile(c, x, y, w, h, code, r=None):
    """origin_tile()'s gradient (wireframes.py), topped with a small drawn
    coffee bag instead of a two-letter code watermark. Letters read as an
    avatar/initial -- the metaphor for a *person* -- which is the wrong
    association for produce you can hold; a generated figure reads as "this
    is coffee" on sight instead. The gradient is still seeded off `code`, so
    tiles keep their per-bean colour variety.

    A loose bean cluster was the first pass here; a bag reads as *the thing
    on your shelf* rather than raw produce, and it's what every specialty
    roaster's own product photography actually shows. So the figure keeps
    real roaster-bag conventions: a gusseted stand-up pouch, a folded/
    crimped top seal (the pleat creases), and a circular one-way degassing
    valve -- the cues that make a Stumptown or Blue Bottle bag legible as
    "coffee" before you read a word on it.

    Second pass, on rendering technique rather than subject: the first
    drawn bag was filled, dark-outlined, multi-stroke-weight line art --
    closer to a Material stock icon than to anything else in this app.
    can_boy() below already sets this app's own convention for generated
    figures: white line only, flat, on the brand green, no filled shapes.
    This bag now follows that same recipe so the two pieces of generated
    art read as siblings instead of two different illustration systems.

    The old label patch (a filled rounded-rect swatch behind a stamped cup
    pictogram -- steam wisps, handle, an origin rule) is dropped for the
    same reason: it was the most Material-icon-shaped part of the figure,
    it added a third fill colour the rest of the mark doesn't use, and its
    detail didn't survive down to the 72dp list tile anyway. In its place:
    the bean's own origin `code`, stamped in bold Fredoka. That's the same
    idiom can_boy uses to stamp "Can" in its belly from the shipped
    wordmark, extended here to a per-bean mark -- two bold letters read at
    any tile size a multi-stroke pictogram can't, and unlike the old cup
    (identical on every bag) it makes the mark carry real information.

    The figure is also scaled to fill its tile more fully and clipped to
    the tile's own rounded rect, rather than floating at a fixed size in
    the middle of a padded field. A tall, narrow pouch silhouette centred
    in the 152x84 wide grid tile left a lot of dead gradient down both
    sides; filling closer to the frame -- like a tight product photo, not
    a centred spot icon -- reads as a photo stand-in rather than a logo.
    """
    r = wf.R_MD if r is None else r
    gid = c.uid("bt")
    seed = sum(ord(ch) for ch in code)
    a = ["#DCEFDD", "#D2ECD8", "#E3F3E1", "#CDE9D2"][seed % 4]
    b = ["#4C9A5B", "#3E8B4C", "#5AAE68", "#347A44"][(seed // 3) % 4]
    c.defs.append(f'<linearGradient id="{gid}" x1="0" y1="0" x2="0.9" y2="1">'
                  f'<stop offset="0" stop-color="{a}"/>'
                  f'<stop offset="1" stop-color="{b}"/></linearGradient>')
    wf.rect(c, x, y, w, h, f"url(#{gid})", r)

    # clip to the tile's own rounded rect so the figure below can be scaled
    # up to fill the frame -- like a tight product photo -- without
    # spilling past the card edge into whatever sits behind it
    cid = c.uid("btc")
    c.defs.append(f'<clipPath id="{cid}"><rect x="{x}" y="{y}" width="{w}" '
                  f'height="{h}" rx="{r}"/></clipPath>')

    m = min(w, h)
    s = m / 100 * 1.3   # fills the tile edge to edge at both tile shapes
    cx0, cy0 = x + w / 2, y + h / 2
    c.add(f'<g clip-path="url(#{cid})">')
    c.add(f'<g transform="translate({cx0:.1f} {cy0:.1f}) scale({s:.3f})" '
          f'fill="none" stroke="#FFFFFF" stroke-linecap="round" '
          f'stroke-linejoin="round">')
    # body: slightly wider at the base, like a gusseted stand-up pouch
    c.add('<path d="M-24 -30 Q-24 -36 -18 -36 L18 -36 Q24 -36 24 -30 '
          'L26 26 Q26 34 18 34 L-18 34 Q-26 34 -26 26 Z" stroke-width="4.4"/>')
    # folded top seal, with pleat creases
    c.add('<path d="M-19 -36 Q-19 -42 -13 -42 L13 -42 Q19 -42 19 -36" '
          'stroke-width="4.4"/>')
    for lx in (-10, 0, 10):
        c.add(f'<path d="M{lx} -41 L{lx+3} -37" stroke-width="2.4"/>')
    # one-way degassing valve -- a ring only, no filled centre dot, so the
    # figure stays true to can_boy's "line only, nothing solid" rule
    c.add('<circle cx="10" cy="-20" r="6" stroke-width="3"/>')
    c.add('</g>')
    c.add('</g>')

    # origin code, stamped in the belly -- can_boy's own idiom (the shipped
    # wordmark reused in its belly), extended to a per-bean mark here
    wf.text(c, cx0, cy0 + s * 10, code.upper(), "titleMedium", "#FFFFFF",
             "middle", family=HEADLINE, size=s * 30, weight=700)


# -------------------------------------------------------------- 00 home ----
# The mean of the seven sessions in +1_sessions -- i.e. what
# repo.get_average_flavor_scores() would return over that same log, weighted
# the way the log actually is (Ethiopia natural 4, Colombia washed 2,
# Guatemala washed 1). So it is close to BEAN_FLAVOR (wireframes.py: the
# single Ethiopia bean profile the bean pages draw) but pulled flatter and
# nuttier by the two washed coffees -- which is the whole point of the Home
# chart: it is the *shelf's* signature, not one bean's.
MY_FLAVOR = [3.7, 2.8, 2.0, 3.9, 2.6, 1.5, 1.9, 1.7, 0.7, 2.5, 2.3]


def home(beans=None):
    """Home once at least one bean profile exists: the empty state's single
    CTA (home_empty) is replaced by full-width bean profile cards in a
    single column.

    This was chosen over a -1_can_drink-style 2-up block grid after building
    both (the grid lived here first; see git history / 00_home_1 in past
    revisions if it needs re-examining). The grid borrows -1_can_drink's
    language, which fits that page well -- browsing many roasters' products
    is a discovery task, and a photo-led grid is the right pattern for
    discovery. Home isn't that: it's a handful of bags someone already
    owns, not a catalogue to browse. A list trades density (fewer beans per
    screen) for room per bean -- a bigger bag_tile(), a clearer single tap
    target, a chevron instead of a same-sized twin -- which is the right
    trade once the collection itself is small. bean_row() (wireframes.py's
    pre-scheme-e sketch of this same idea) made the same call originally.

    Where -1_can_drink's cards top out with photo() (a plausible stand-in
    for a real roaster photo scraped off the web), these top out with
    bag_tile() instead: a bean a user just added has no photo yet, and
    photo()'s gradient is a *placeholder for one that will exist* -- exactly
    wrong for a card that may never get one. bag_tile() draws a small figure
    (a coffee bag) in place of a real photo rather than falling back to
    text -- see its docstring for why that beats origin_tile()'s two-letter
    watermark.

    Below the list sit the two summary panes coffee-can's own main window
    shows side by side (gui/main_window.py: _build_activity_pane /
    _build_flavor_profile_pane) — the contribution calendar and the "My
    Flavor" radar of repo.get_average_flavor_scores(). Side by side is not
    available at 360dp, so they stack; keeping both *visible* rather than
    hiding one behind a segmented control is the point, since on the desktop
    they are read together as one summary of the same log.

    That costs the fourth bean card: a usable radar needs ~180dp of height
    (below about r=50 the eleven labels crowd into the polygon and the shape
    stops being readable), which is two bean cards' worth. So the list shows
    three and hands the rest to a "See all" row — the same affordance, in the
    same place, that main_window.py puts under its own three shelf cards.
    The `beans` sample stays four long so it still agrees with
    +1_sessions' log; only what fits above the fold changed.

    `beans` is a sequence of (name, roast_meta, brew_count, origin_code);
    defaults to a small sample so the page renders on its own.
    """
    beans = beans or [
        ("Ethiopia Guji Natural", "Natural · Roasted 28 Jul", 4, "ET"),
        ("Colombia Huila Washed", "Washed · Roasted 20 Jul", 2, "CO"),
        ("Kenya Nyeri AB", "Washed · Roasted 02 Aug", 0, "KE"),
        ("Guatemala Huehue", "Washed · Roasted 15 Jul", 1, "GT"),
    ]
    c = wf.Canvas("Home — scheme E")
    wf.status_bar(c)
    wf.top_bar(c, "Coffee Can", brand=True)
    wf.section(c, 112, "Your beans", "Search")

    card_w, card_h, tile, row_gap = W - 2 * wf.GUTTER, 72, 64, 6
    start_y, shown = 124, 3
    for i, (name, meta, sessions, code) in enumerate(beans[:shown]):
        cx, cy = wf.GUTTER, start_y + i * (card_h + row_gap)
        wf.card(c, cy, card_h, x=cx, w=card_w)
        bag_tile(c, cx + 12, cy + 4, tile, tile, code, r=wf.R_MD)
        tx = cx + 12 + tile + 14
        wf.text(c, tx, cy + 26, name, "titleMedium", size=14)
        wf.text(c, tx, cy + 42, meta, "bodyMedium", wf.C["onSurfaceVariant"], size=11)
        if sessions:
            label = "1 brew" if sessions == 1 else f"{sessions} brews"
            wf.rect(c, tx, cy + 49, len(label) * 6.2 + 20, 16, wf.C["primaryContainer"], wf.R_XS)
            wf.text(c, tx + 10, cy + 61, label, "labelSmall", wf.C["onPrimaryContainer"])
        else:
            wf.rect(c, tx, cy + 49, 92, 16, wf.C["surfaceContainer"], wf.R_XS)
            wf.text(c, tx + 10, cy + 61, "No brews yet", "labelSmall", wf.C["onSurfaceVariant"])
        wf.path(c, f"M{cx+card_w-24} {cy+card_h/2-5} l5 5 l-5 5", stroke=wf.C["outline"], sw=1.6)

    list_bottom = start_y + shown * card_h + (shown - 1) * row_gap
    # Under the cards, not beside the section heading: it reads as "more of
    # the same shelf" rather than a header action, and it doesn't compete
    # with "Search" for the heading row.
    wf.text(c, W - 20, list_bottom + 18, f"See all {len(beans)} beans",
            "labelLarge", wf.C["primaryText"], "end")

    wf.section(c, list_bottom + 48, "Brewing activity")
    wf.card(c, list_bottom + 60, 140)
    wf.heatmap(c, 28, list_bottom + 92, 304)

    flavor_y = list_bottom + 60 + 140 + 24
    wf.section(c, flavor_y, "My flavor")
    # coffee-can captions this chart *under* the polygon; at this size the
    # eleven axis labels reach the card's bottom edge, so the caption moves
    # up onto the heading row instead of being squeezed between them. It
    # stays onSurfaceVariant rather than taking section()'s green action
    # slot -- it explains the chart, it doesn't navigate anywhere.
    wf.text(c, W - 20, flavor_y, "Average across 7 sessions", "labelSmall",
            wf.C["onSurfaceVariant"], "end")
    wf.card(c, flavor_y + 12, 178)
    # vizSeries, not primary: the palette reserves primary for "touch this"
    # or "on target", never for how much of a thing there is. The net drops
    # to vizGrid so the eleven labels stay the readable layer.
    wf.radar11(c, 180, flavor_y + 98, 60, MY_FLAVOR, wf.C["vizSeries"],
               wf.C["vizInk"], fill_op=0.18, grid=wf.C["vizGrid"])

    # The page now runs to the gesture bar, so the FAB floats over content the
    # way it always would on a scrolling Home -- parked in the flavor card's
    # bottom-right corner, which the radar's own linework never reaches (its
    # labels stop at x~272).
    fab_cy = 730
    wf.circle(c, 312, fab_cy, 28, wf.C["primary"], stroke=wf.C.get("primaryOutline"))
    wf.path(c, f"M300 {fab_cy} h24 M312 {fab_cy - 12} v24", stroke=wf.C["onPrimary"], sw=2.6)
    wf.gesture_bar(c)
    return c


# ------------------------------------------------------------ 01b home ----
def home_empty(headline_font=None, shake=0.0):
    """First run, no beans yet. Layout unchanged from the draft; the avatar
    defaults to R and the headline carries the display face.

    `shake` (-1..1) offsets the CTA for the idle attention wiggle."""
    hf = headline_font or HEADLINE
    c = wf.Canvas("Home · empty state — scheme E")
    wf.status_bar(c)
    wf.top_bar(c, "Coffee Can", brand=True)
    wf.logo(c, 180, 286, 100)
    wf.text(c, 180, 400, "No beans yet", "headlineMedium", wf.C["onSurface"],
            "middle", family=hf, size=34)
    for i, ln in enumerate(("Add the bag you're brewing this week",
                            "and start keeping the log.")):
        wf.text(c, 180, 436 + i * 24, ln, "bodyLarge", wf.C["onSurfaceVariant"],
                "middle")
    bx, by, bw = 68, 500, 224
    if shake:
        # ~5dp of travel with a hair of counter-rotation: a nudge, not a buzz
        cx, cy = bx + bw / 2, by + 24
        c.add(f'<g transform="translate({6 * shake:.2f} 0) '
              f'rotate({1.0 * shake:.2f} {cx} {cy})">')
    wf.button(c, bx, by, bw, "Add your first bean")
    if shake:
        c.add("</g>")
    wf.gesture_bar(c)
    return c


# --------------------------------------------------------- 0.5 add-a-bean ---
# The hero grew to fit can_boy_camera(), and everything under it moves down by
# the difference. Kept as constants because the shift has to be applied to
# every y below the hero and a stray literal would silently break the column.
_HERO_H = 180
_SHIFT = _HERO_H - 140


def _win(p, a, b, shape=1.0):
    """A half-sine window over [a, b], zero outside it AND zero at both ends
    -- so anything driven by it starts and finishes at rest inside the cycle,
    which is what keeps the loop seamless without hand-tuning the last frame."""
    if not (a <= p <= b):
        return 0.0
    return math.sin(math.pi * (p - a) / (b - a)) ** shape


def _shutter_pose(p):
    """Phase (0..1) -> can_boy_camera()'s five knobs. The beat is aim, press,
    flash, recoil, settle -- the recoil window deliberately outlasts the
    flash, so the body is still rocking back after the burst has gone, the
    way a real flinch trails its trigger."""
    aim = 2.2 * math.sin(2 * math.pi * p)             # continuous idle sway
    press = 1.5 * _win(p, 0.30, 0.52, 0.7)            # camera dips into the shot
    return {
        "arm_angle": -3.0 + aim + 2.0 * press,
        "cam_tilt": -6.0 + 1.5 * aim,
        "press": press,
        "flash": _win(p, 0.44, 0.68, 0.55),
        "lean": -2.6 * _win(p, 0.46, 0.86, 0.8),
    }


def bean_profile_empty(p=0.53):
    """The blank "add a bean" form: what 0.6/0.6b look like before any data
    exists.

    `p` is the shutter animation's phase; the default freezes it mid-burst,
    which is the frame that says "camera" loudest in a still deck.
    Reached by tapping Add bean from Home (00_home_empty's CTA, or the top
    bar's add action once beans exist).

    02b buries its "Scan label" action as one more tile in the Documents
    grid, well down the second scroll page — fine for a bean that already
    has data, but for a brand-new one that tile *is* the fastest way to fill
    in the rest of the form, so it moves to the page's first action instead
    of competing with fields the user hasn't touched yet.

    02's photo hero has nothing to show yet either (no bag has been scanned),
    so that space becomes the scan prompt rather than staying empty.
    """
    pose = _shutter_pose(p)
    c = wf.Canvas("Bean profile — empty (0.5)")
    wf.status_bar(c)
    wf.top_bar(c, "New bean", back=True)

    wf.rect(c, wf.GUTTER, 104, W - 2 * wf.GUTTER, _HERO_H,
            wf.C["secondaryContainer"], wf.R_LG)
    # The hero used to draw a bare camera outline -- a rect and a lens circle
    # floating on their own. That exact camera is now in can-boy's hands, so
    # the prompt shows the app's own character doing the thing it is asking
    # you to do. It costs 40dp of hero height (140 -> 180) plus _SHIFT on
    # everything below; a disc much smaller than this and the camera stops
    # reading as a camera, which would defeat the point.
    can_boy_camera(c, 180, 168, 108, **pose)
    # "Click me to scan", not "Scan label": the mascot is now the tap target
    # and the label should say so. It also stops the hero reading as a
    # caption under an illustration.
    wf.text(c, 180, 244, "Click me to scan", "titleMedium",
            wf.C["onSecondaryContainer"], "middle")
    wf.text(c, 180, 266, "Point your camera at the bag to fill this in",
            "labelSmall", wf.C["onSecondaryContainer"], "middle")

    wf.text(c, 180, 268 + _SHIFT, "or enter it by hand", "labelMedium",
            wf.C["outline"], "middle")

    wf.textfield(c, wf.GUTTER, 286 + _SHIFT, W - 2 * wf.GUTTER, "Bean name", "")
    rows = (("Variety", "", "Altitude", ""),
            ("Roaster", "", "Producer", ""),
            ("Process", "", "Roast date", ""))
    for i, (l1, v1, l2, v2) in enumerate(rows):
        ry = 374 + _SHIFT + i * 52
        wf.field(c, 20, ry, 145, l1, v1, placeholder=True)
        wf.field(c, 195, ry, 145, l2, v2, placeholder=True)

    # "Radar", not "Flavor" -- 0.6/0.6b name this same block after the chart
    # in it, and the empty state has to agree with the state it becomes.
    wf.section(c, 546 + _SHIFT, "Radar", "Set manually")
    wf.card(c, 560 + _SHIFT, 90)
    wf.text(c, 180, 598 + _SHIFT, "Log a brew to start building this bean's",
            "bodyMedium", wf.C["onSurfaceVariant"], "middle")
    wf.text(c, 180, 618 + _SHIFT, "flavor profile", "bodyMedium",
            wf.C["onSurfaceVariant"], "middle")

    wf.button(c, wf.GUTTER, 674 + _SHIFT, W - 2 * wf.GUTTER, "Save bean")
    wf.gesture_bar(c)
    return c


# ----------------------------------------------------------- 0.51 camera ---
# 08 / 08b (wireframes.camera / camera_permission) brought into scheme E and
# numbered off 0.5, because that is what reaches them: tapping "Click me to
# scan" on 0.5 opens 0.51, and 0.51b is what you get instead when the camera
# permission has been denied.
def camera():
    """0.51: the capture viewfinder. Carried over from the wireframe as-is --
    a camera screen is the system's visual language, not the app's, and
    scheme E's palette has no business on a live viewfinder."""
    c = wf.Canvas("Camera capture — scheme E (0.51)", bg=wf.C["dSurface"])
    wf.rect(c, 0, 0, W, H, wf.C["camGround"])
    wf.status_bar(c, dark=True)
    wf.rect(c, 0, 0, W, 96, wf.C["scrim"], opacity=0.45)
    wf.rect(c, 0, 620, W, 180, wf.C["scrim"], opacity=0.45)
    wf.path(c, "M29 61 l14 14 M43 61 l-14 14", stroke="#FFFFFF", sw=2)
    wf.text(c, 180, 74, "Scan bean label", "titleMedium", "#FFFFFF", "middle")
    for (ax, ay, dx, dy) in ((44, 210, 1, 1), (316, 210, -1, 1),
                             (44, 560, 1, -1), (316, 560, -1, -1)):
        wf.path(c, f"M{ax} {ay+28*dy} v{-28*dy} h{28*dx}", stroke=wf.C["dPrimary"], sw=3)
    wf.text(c, 180, 600, "Fill the frame with the label", "bodyMedium", "#FFFFFF",
            "middle")
    wf.circle(c, 180, 700, 34, "none", stroke="#FFFFFF", sw=3)
    wf.circle(c, 180, 700, 27, "#FFFFFF")
    wf.rect(c, 48, 676, 48, 48, "#FFFFFF", wf.R_SM, opacity=0.16)
    wf.photo(c, 52, 680, 40, 40, r=wf.R_XS)
    wf.text(c, 72, 742, "Photos", "labelSmall", "#FFFFFF", "middle")
    wf.circle(c, 288, 700, 24, "#FFFFFF", opacity=0.16)
    wf.flash(c, 288, 700)
    wf.text(c, 288, 742, "Flash", "labelSmall", "#FFFFFF", "middle")
    wf.gesture_bar(c, dark=True)
    return c


def camera_permission():
    """0.51b: permission denied.

    The wireframe drew a struck-through camera glyph here -- a Material
    "feature off" icon, the same rect-and-lens pair 0.5's hero used to
    have. Scheme E has can-boy for exactly this moment: he is already the
    one holding the camera on 0.5, so he is the one it was taken away from.
    A slumped mascot with a broken heart says "you turned me off" in a way
    a struck-through glyph cannot, and it keeps the two screens telling one
    story rather than sharing a stock icon.

    The copy is unchanged. The illustration carries the feeling; the words
    still have to carry the fix, and "turn it back on in Settings" is the
    fix.
    """
    c = wf.Canvas("Camera · permission denied — scheme E (0.51b)")
    wf.status_bar(c)
    wf.top_bar(c, "Scan bean label", back=True)
    can_boy_sad(c, 180, 248, 164)
    wf.text(c, 180, 372, "Camera is off", "headlineMedium", wf.C["onSurface"],
            "middle", family=HEADLINE, size=30)
    for i, ln in enumerate(("Scanning a label needs the camera. You",
                            "turned it off — you can turn it back on in",
                            "Settings.")):
        wf.text(c, 180, 408 + i * 22, ln, "bodyLarge", wf.C["onSurfaceVariant"],
                "middle")
    wf.button(c, 80, 490, 200, "Open Settings")
    wf.button(c, 60, 550, 240, "Pick a photo instead", "tonal")
    wf.text(c, 180, 628, "Picking a photo needs no permission at all.", "labelSmall",
            wf.C["onSurfaceVariant"], "middle")
    wf.text(c, 180, 650, "You can also type everything by hand.", "labelSmall",
            wf.C["onSurfaceVariant"], "middle")
    wf.gesture_bar(c)
    return c


# ------------------------------------------------------- 0.6 bean profile ---
# 02 / 02b (wireframes.bean_detail / bean_detail_lower) brought into scheme E,
# which is where 0.5 above always pointed: 0.5 is this page before any data
# exists, 0.6 is the same destination once it has some. Numbered off-axis
# beside 0.5 rather than kept as "02" because scheme E numbers by the swipe
# axis, and this page is reached by tapping a bean on Home, not by swiping.
#
# The layout, hero treatment and score-sheet fields are unchanged from the
# wireframe -- the two blocks that changed are:
#
#   Flavor -> Radar     The eleven axes as one polygon rather than eleven
#                       bars. flavor_bars() ranks and reads values off;
#                       radar11() gives the bean one shape you recognise
#                       again on the next bag, which is what a *profile*
#                       page is for. It also lets the block carry all eleven
#                       axes in the space three bars used to take, so 02's
#                       "all 11 axes below" pointer is gone with it.
#
#   Documents -> Images That block was drawn as a shelf of scanned label
#                       *documents* with a "Scan label" tile, i.e. an OCR
#                       source -- but scanning-to-fill-the-form is 0.5's job
#                       (its hero prompt), and doing it twice made the label
#                       photo look like a document you file rather than a
#                       picture you keep. It is now the bean's image
#                       gallery, which is a real coffee-can feature and not
#                       a new one: repo.add_bean_image() /
#                       paths.images_dir(bean_id), up to
#                       paths.MAX_IMAGES_PER_BEAN (5) per bean, ordered by
#                       `position`. So "Add img" attaches a photo (camera or
#                       picker) to this bean; it does not read anything off
#                       it. The hero at the top of 0.6 is image #1 of the
#                       same set.
#
# Design is untouched on both -- same card, same tilted stack, same tonal
# add-tile in the same slot. Only the chart inside the first and the words
# in both.
# The one line of copy the empty radar carries, on 0.6 and 0.6b alike. It
# sits under the section heading rather than inside the card because 0.6's
# card has no room -- at r=62 the top axis label already touches the card's
# top edge -- and because 0.6/0.6b are the same page at two scroll offsets:
# a sentence that moved from above the card to inside it as you scrolled
# would be two different pages, not one.
_RADAR_EMPTY_NOTE = "Log a brew and this fills itself in — or Set manually."


def bean_detail(empty=False):
    """0.6: the saved bean profile, first scroll page — photo hero over the
    score-sheet fields, with the radar starting to show above the fold.

    The radar card deliberately runs past y=800: this is the top of a
    scrolling page, and a card cut by the fold says "keep going" where a
    card that ends neatly above it says "this is all there is". 0.6b picks
    that same card up in full.

    `empty=True` is 0.6_empty (see bean_detail_empty); everything above the
    Radar heading is shared verbatim, which is the point of the flag.
    """
    c = wf.Canvas("Bean profile — scheme E (0.6)")
    wf.photo(c, 0, 0, W, 300, r=0)
    gid = c.uid("fade")
    c.defs.append(f'<linearGradient id="{gid}" x1="0" y1="0" x2="0" y2="1">'
                  f'<stop offset="0" stop-color="{wf.C["surface"]}" stop-opacity="0"/>'
                  f'<stop offset="1" stop-color="{wf.C["surface"]}" stop-opacity="0.9"/>'
                  f'</linearGradient>')
    wf.rect(c, 0, 170, W, 130, f"url(#{gid})")
    tid = c.uid("top")                  # keeps the status bar legible on any photo
    c.defs.append(f'<linearGradient id="{tid}" x1="0" y1="0" x2="0" y2="1">'
                  f'<stop offset="0" stop-color="{wf.C["scrim"]}" stop-opacity="0.55"/>'
                  f'<stop offset="1" stop-color="{wf.C["scrim"]}" stop-opacity="0"/>'
                  f'</linearGradient>')
    wf.rect(c, 0, 0, W, 96, f"url(#{tid})")
    wf.status_bar(c, dark=True)
    for cx in (36, 324):
        wf.circle(c, cx, 52, 20, wf.C["scrim"], opacity=0.45)
    wf.path(c, "M40 45 l-7 7 l7 7", stroke="#FFFFFF", sw=2)
    wf.path(c, "M324 59 v-13 m0 -1 l-5 5 m5 -5 l5 5", stroke="#FFFFFF", sw=2)
    wf.path(c, "M316 53 v7 h16 v-7", stroke="#FFFFFF", sw=2)

    wf.sheet(c, 272)
    wf.text(c, 20, 322, "Ethiopia Guji", "headlineMedium")
    wf.text(c, 20, 354, "Natural", "headlineMedium")
    wf.text(c, 20, 380, "Guji, Ethiopia · Natural · Roasted 28 Jul", "bodyMedium",
            wf.C["onSurfaceVariant"])
    wf.line(c, 20, 400, 340, 400)
    rows = (("Variety", "Heirloom", "Altitude", "1 950 m"),
            ("Roaster", "Belleville", "Producer", ""),
            ("Process", "Natural", "Roast date", "28 Jul 2026"))
    for i, (l1, v1, l2, v2) in enumerate(rows):
        ry = 428 + i * 60
        wf.field(c, 20, ry, 145, l1, v1)
        wf.field(c, 195, ry, 145, l2, v2)

    wf.section(c, 616, "Radar", "Set manually")
    if empty:
        wf.text(c, 20, 634, _RADAR_EMPTY_NOTE, "labelSmall", wf.C["onSurfaceVariant"])
        # The note costs 16dp, and the net gives it back out of its own
        # radius: 62 -> 53, the largest that still lands the bottom axis
        # labels where the populated page's land (~y796), so the fold cuts
        # both states of this page in the same place. An empty net has no
        # polygon to read off it, so radius is the cheapest thing on this
        # card to spend.
        wf.card(c, 646, 190)
        wf.radar11(c, 180, 723, 53)
    else:
        wf.card(c, 630, 190)
        wf.radar11(c, 180, 715, 62, wf.BEAN_FLAVOR, wf.C["vizSeries"], wf.C["vizInk"],
                   fill_op=0.18, grid=wf.C["vizGrid"])
    return c


def bean_detail_empty():
    """0.6 for a bean with nothing brewed yet: the profile is complete —
    name, origin, variety, roaster, process, roast date, photo — and the only
    thing missing is the log. Reached the same way 0.6 is, by tapping a bean
    on Home; a bean saved from 0.5 lands here and stays here until its first
    session.

    Against 0.6, exactly two things change and everything above the Radar
    heading is untouched. The net goes grey and loses its polygon
    (radar11(values=None) — see its docstring for why an empty net beats a
    row of zeros), and a line under the heading says what the grey means and
    how to end it.

    The fold still cuts the radar card, deliberately, and cuts it harder in
    this state than in the populated one. A card that ended neatly above
    y=800 here would say "nothing logged, and nothing below either" — false,
    since 0.6b still holds this bean's images and the invitation to brew.
    Cut, it says "keep going", and what you find by going is the mascot
    asking for a cup.
    """
    return bean_detail(empty=True)


def bean_detail_lower():
    """0.6b: the same page scrolled — the radar at full size, the bean's
    images, and its sessions."""
    c = wf.Canvas("Bean profile · lower — scheme E (0.6b)")
    wf.status_bar(c)
    wf.top_bar(c, "Ethiopia Guji Natural", back=True, actions=("share",))

    wf.section(c, 116, "Radar", "Set manually")
    wf.card(c, 130, 326)
    wf.radar11(c, 180, 293, 92, wf.BEAN_FLAVOR, wf.C["vizSeries"], wf.C["vizInk"],
               fill_op=0.18, grid=wf.C["vizGrid"])
    wf.text(c, 20, 474, "Averaged from 4 sessions · fixed axis order, 0–5 scale",
            "labelSmall", wf.C["onSurfaceVariant"])

    wf.section(c, 512, "Images")
    for x, rot in ((20, -1.5), (104, 1.2), (188, -0.8)):
        c.add(f'<g transform="rotate({rot} {x+38} {572})">')
        wf.rect(c, x + 2, 526, 76, 96, wf.C["scrim"], 2, opacity=0.10)
        wf.rect(c, x, 524, 76, 96, wf.C["cardSurface"], 2, stroke=wf.C["outlineVariant"])
        for k in range(5):
            wf.line(c, x + 9, 544 + k * 13, x + 67 - (k % 2) * 16, 544 + k * 13,
                    wf.C["outlineVariant"], 2)
        c.add("</g>")
    wf.rect(c, 276, 524, 68, 96, wf.C["secondaryContainer"], wf.R_SM)
    wf.path(c, "M304 562 h12 M310 556 v12", stroke=wf.C["onSecondaryContainer"], sw=2)
    wf.text(c, 310, 588, "Add img", "labelSmall", wf.C["onSecondaryContainer"], "middle")

    wf.section(c, 652, "Sessions", "Ask AI")
    for i, (d, sub) in enumerate((("30 Jul", "V60 · 15.0 g · 4.5 · well extracted"),
                                  ("25 Jul", "Kalita · 16.0 g · 4.0 · slightly under"))):
        ry = 664 + i * 48
        wf.text(c, 20, ry + 20, d, "titleMedium")
        wf.text(c, 20, ry + 40, sub, "bodyMedium", wf.C["onSurfaceVariant"], size=13)
        wf.line(c, 20, ry + 48, 340, ry + 48)
    wf.circle(c, 312, 712, 28, wf.C["primary"], stroke=wf.C.get("primaryOutline"))
    wf.path(c, "M300 712 h24 M312 700 v24", stroke=wf.C["onPrimary"], sw=2.6)
    wf.gesture_bar(c)
    return c


def bean_detail_lower_empty():
    """0.6b for the same unbrewed bean as 0.6_empty: the radar with no series
    in it, the bean's images — which exist, this state is about missing
    *brews*, not a missing profile — and a Sessions block with nothing to
    list. Reached by scrolling 0.6_empty.

    Block order is 0.6b's, unchanged: Radar, Images, Sessions. Order is what
    makes this the same page as its populated twin; only the heights flex.
    And they have to flex, because two 48dp session rows become an
    illustration block roughly twice that, on a page whose budget is fixed at
    800dp. The 90dp comes out of the radar card (326 -> 232, radius 92 -> 68).
    That is not a grudging trim: a card that big with no polygon in it is
    mostly white, which is the "blank card" failure this state has to avoid,
    and the axis contract that makes the chart worth keeping — eleven named
    axes, fixed order, five rings — survives the smaller radius intact.

    The caption under the card is rewritten. "Averaged from 4 sessions" is a
    lie here, and restating "no sessions" would be the third time the page
    said it, so it keeps only the half that is still true and still useful:
    the axis order and the 0–5 scale, which is what lets a reader compare
    this bean's shape against the next one's.

    Sessions is the page's emotional beat, so it gets the space the radar
    gave up: can-boy brewing a V60 at 132dp — over the 120dp the figure needs
    to read, since the block could afford it — under "No brews yet", the same
    phrasing 00_home_empty and Home's own bean chips already use. The copy
    names the plus button rather than restating the heading, and the FAB
    stays exactly where 0.6b parks it (312, 712): it is the one thing on this
    page that changes the state, and moving it between states would cost the
    muscle memory that makes it obvious. Nothing else is placed inside its
    corner, so the mascot and the copy clear it without a fight.
    """
    c = wf.Canvas("Bean profile · lower — scheme E (0.6b, no sessions)")
    wf.status_bar(c)
    wf.top_bar(c, "Ethiopia Guji Natural", back=True, actions=("share",))

    wf.section(c, 116, "Radar", "Set manually")
    wf.text(c, 20, 134, _RADAR_EMPTY_NOTE, "labelSmall", wf.C["onSurfaceVariant"])
    wf.card(c, 148, 232)
    wf.radar11(c, 180, 264, 68)
    wf.text(c, 20, 398, "Fixed axis order, 0–5 scale", "labelSmall",
            wf.C["onSurfaceVariant"])

    wf.section(c, 430, "Images")
    for x, rot in ((20, -1.5), (104, 1.2), (188, -0.8)):
        c.add(f'<g transform="rotate({rot} {x+38} {490})">')
        wf.rect(c, x + 2, 444, 76, 96, wf.C["scrim"], 2, opacity=0.10)
        wf.rect(c, x, 442, 76, 96, wf.C["cardSurface"], 2, stroke=wf.C["outlineVariant"])
        for k in range(5):
            wf.line(c, x + 9, 462 + k * 13, x + 67 - (k % 2) * 16, 462 + k * 13,
                    wf.C["outlineVariant"], 2)
        c.add("</g>")
    wf.rect(c, 276, 442, 68, 96, wf.C["secondaryContainer"], wf.R_SM)
    wf.path(c, "M304 480 h12 M310 474 v12", stroke=wf.C["onSecondaryContainer"], sw=2)
    wf.text(c, 310, 506, "Add img", "labelSmall", wf.C["onSecondaryContainer"], "middle")

    wf.section(c, 570, "Sessions", "Ask AI")
    can_boy_v60(c, 180, 648, 132)
    wf.text(c, 180, 744, "No brews yet", "titleLarge", wf.C["onSurface"], "middle",
            family=HEADLINE)
    wf.text(c, 180, 768, "Go brew a cup, then tap + to log it.", "bodyMedium",
            wf.C["onSurfaceVariant"], "middle")
    wf.circle(c, 312, 712, 28, wf.C["primary"], stroke=wf.C.get("primaryOutline"))
    wf.path(c, "M300 712 h24 M312 700 v24", stroke=wf.C["onPrimary"], sw=2.6)
    wf.gesture_bar(c)
    return c


# ----------------------------------------------------------------- can-boy --
# A separate mascot mark, distinct from the shipped logo (wf.logo /
# coffee_can/assets/icon.svg, unmodified). White line only, flat, on its own
# green disc so the white reads against this page's light background. Arms
# and legs are each a single stroked line -- no double green+white pass, no
# filled hand/foot caps. The "Can" lettering is not redrawn in outline: it
# reuses the shipped wordmark's own solid glyphs (wf._LOGO_WORD) rescaled
# into the belly, so the text matches the real logo exactly.
def can_boy(c, cx, cy, size, bean_angle=0.0):
    """Spec'd in a 100x100 box; `size` is the rendered edge in dp.

    `bean_angle` pivots the raised arm -- can-boy's own left hand, screen
    right since he faces the viewer -- about the shoulder (degrees); the
    bean rides along with it. The shake animation drives this frame to frame.
    """
    g = size / 100.0
    c.add(f'<g transform="translate({cx - size/2:.2f} {cy - size/2:.2f}) scale({g:.4f})">')
    c.add(f'<circle cx="50" cy="50" r="50" fill="{wf.BRAND_MARK}"/>')

    # the figure itself is drawn smaller than the disc and shrunk toward its
    # centre: the raised arm swings through +-15 deg, and at full size that
    # carried the hand and bean past the disc's edge
    c.add('<g transform="translate(50 50) scale(0.82) translate(-50 -50)">')
    c.add('<g fill="none" stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round">')
    # limbs, drawn under the can so its outline overlaps the shoulder/hip join
    c.add('<g stroke-width="4.2">')
    c.add('<path d="M30 40 Q19 44 17 55"/>')   # right arm, hand on hip
    c.add('<path d="M41 75 L37 90"/>')          # left leg
    c.add('<path d="M59 75 L63 90"/>')          # right leg
    c.add('</g>')
    # left arm, raised, holding the bean -- pivots as one piece at the
    # shoulder (70,38) so the wave and the bean shake together, not the bean
    # wobbling in a fixed hand
    c.add(f'<g transform="translate(70 38) rotate({bean_angle:.2f})">')
    c.add('<path d="M0 0 Q11 -9 9 -22" fill="none" stroke="#FFFFFF" stroke-width="4.2"/>')
    # the bean, at the hand's rest position (9,-22) relative to the shoulder
    # -- an S crease with unequal bulges reads as a bean seam rather than an eye
    c.add('<g transform="translate(9 -22) rotate(-10)" stroke="#FFFFFF" stroke-width="2.4">')
    c.add('<ellipse cx="0" cy="0" rx="4.6" ry="6.2" fill="none"/>')
    c.add('<path d="M0.5 -4.5 C1.8 -2.1 -1.8 1.6 0.2 4.5" fill="none" stroke-width="1.6"/>')
    c.add('</g>')
    c.add('</g>')
    # the can itself: lid + a barrel-bulged body, funky rather than a
    # straight-sided box so it reads as a can and not a carton
    c.add('<g stroke-width="5.2">')
    c.add('<path d="M33 27 C 29 41, 29 60, 33 74 C 40 78, 60 78, 67 74 '
          'C 71 60, 71 41, 67 27"/>')
    c.add('<ellipse cx="50" cy="24" rx="19" ry="6.5"/>')
    c.add('</g>')
    # pull tab: a small ring on a short rivet stem
    c.add('<g transform="translate(58 12) rotate(-12)" stroke-width="3">')
    c.add('<ellipse cx="0" cy="0" rx="5.4" ry="3.6"/>')
    c.add('<path d="M0 3.6 L-0.8 7.6"/>')
    c.add('</g>')
    c.add('</g>')

    # 'Can': the shipped wordmark's own solid paths, recentred (their bbox
    # centre is ~63.5,50.3 in the icon's 128 viewBox) and scaled into the belly
    # -- small enough to clear the body outline's stroke width on both sides
    c.add('<g transform="translate(50 57) scale(0.5) translate(-63.54 -50.33)" '
          'fill="#FFFFFF">' + "".join(wf._LOGO_WORD) + '</g>')
    c.add("</g>")  # close the shrink-toward-centre group
    c.add("</g>")


# ------------------------------------------------------ can-boy, variants ---
# Two more poses of the same mark. Both copy can_boy() rather than wrapping
# it, because each has to change a limb the original draws inline -- the
# camera pose replaces the raised bean arm, the sitting pose replaces both
# arms and both legs. Everything that carries the identity is verbatim in
# both: the can path, the lid ellipse, the pull tab, the round caps/joins,
# every stroke weight, and the belly wordmark (wf._LOGO_WORD, never redrawn).
def can_boy_camera(c, cx, cy, size, arm_angle=0.0, cam_tilt=0.0, flash=0.0,
                   lean=0.0, press=0.0):
    """Can-boy taking a photo, for 0.5's scan prompt.

    `arm_angle` pivots the camera arm at the shoulder, `cam_tilt` rolls the
    camera in the hand, `press` dips it on the shutter press, `flash` (0..1)
    drives the burst, `lean` rocks the whole figure about its feet. All five
    rest at 0; bean_profile_frames() drives them.
    """
    g = size / 100.0
    c.add(f'<g transform="translate({cx - size/2:.2f} {cy - size/2:.2f}) scale({g:.4f})">')
    c.add(f'<circle cx="50" cy="50" r="50" fill="{wf.BRAND_MARK}"/>')

    # 0.78 rather than can_boy's 0.82, and the figure slides 8 units left: a
    # camera is a far wider prop than a bean, and held at the bean's height
    # and scale both its corner and the flash crossed the disc edge (measured
    # frame by frame, not eyeballed). Sliding the can left of centre puts the
    # empty half of the disc where the prop and the burst need it, and lets
    # the camera be big enough to actually read as a camera.
    c.add('<g transform="translate(50 50) scale(0.78) translate(-58 -50)">')
    # recoil pivots about the feet, so the shoes stay planted and only the
    # body rocks -- a figure that translated bodily would look like it was
    # sliding, not flinching
    c.add(f'<g transform="rotate({lean:.2f} 50 88)">')
    c.add('<g fill="none" stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round">')

    c.add('<g stroke-width="4.2">')
    c.add('<path d="M30 40 Q19 44 17 55"/>')   # right arm, hand on hip
    c.add('<path d="M41 75 L37 90"/>')          # left leg
    c.add('<path d="M59 75 L63 90"/>')          # right leg
    c.add('</g>')

    # camera arm: shorter and lower than can_boy's bean arm (which reaches to
    # (9,-22)). Held at the bean's height the camera sat up against the lid
    # and the pull tab; at shoulder height it has clear green around it.
    c.add(f'<g transform="translate(70 38) rotate({arm_angle:.2f})">')
    c.add('<path d="M0 0 Q10 -6 8 -12" fill="none" stroke="#FFFFFF" stroke-width="4.2"/>')
    # The camera sits up-right OF the hand rather than centred on it, so the
    # arm's round cap cups its lower-left corner and reads as fingers on the
    # body. Centred, the hand vanished under it and the prop looked stuck to
    # the end of a stick. Body 20x13 with a 4.2 lens: a first pass at 16x11
    # with a 3.4 lens read as an anonymous little box -- at this size the lens
    # has to be a big fraction of the body or "camera" doesn't land.
    c.add(f'<g transform="translate(16 {-18 + press:.2f}) rotate({cam_tilt:.2f})" '
          f'stroke-width="2.6">')
    c.add('<rect x="-10" y="-6.5" width="20" height="13" rx="3"/>')
    c.add('<path d="M-6.5 -6.5 L-5.2 -10 L-0.6 -10 L0.7 -6.5"/>')  # viewfinder hump
    c.add('<circle cx="3" cy="0" r="4.2"/>')                        # lens
    c.add('<path d="M-6.4 -2.2 h2.2" stroke-width="2.2"/>')         # flash window
    c.add('</g>')
    c.add('</g>')

    c.add('<g stroke-width="5.2">')
    c.add('<path d="M33 27 C 29 41, 29 60, 33 74 C 40 78, 60 78, 67 74 '
          'C 71 60, 71 41, 67 27"/>')
    c.add('<ellipse cx="50" cy="24" rx="19" ry="6.5"/>')
    c.add('</g>')
    c.add('<g transform="translate(58 12) rotate(-12)" stroke-width="3">')
    c.add('<ellipse cx="0" cy="0" rx="5.4" ry="3.6"/>')
    c.add('<path d="M0 3.6 L-0.8 7.6"/>')
    c.add('</g>')

    # The burst: five ticks fanning off the lens, away from him. Drawn last so
    # they sit over the arm, and clamped short -- longer and the outermost
    # tick crosses the disc even at this arm height.
    if flash > 0.001:
        lx, ly = 70 + 16 + 3, 38 - 18 + press     # lens, in figure space
        inner = 6.4 + 1.8 * flash
        outer = inner + 2.6 + 5.0 * flash
        c.add(f'<g stroke-width="2.2" opacity="{min(1.0, flash):.3f}">')
        for deg in (-52, -26, 0, 26, 52):
            a = math.radians(deg)
            c.add(f'<path d="M{lx + inner * math.cos(a):.2f} {ly + inner * math.sin(a):.2f} '
                  f'L{lx + outer * math.cos(a):.2f} {ly + outer * math.sin(a):.2f}"/>')
        c.add('</g>')

    c.add('</g>')      # stroke group
    c.add('<g transform="translate(50 57) scale(0.5) translate(-63.54 -50.33)" '
          'fill="#FFFFFF">' + "".join(wf._LOGO_WORD) + '</g>')
    c.add('</g>')      # lean
    c.add('</g>')      # shrink
    c.add('</g>')


def can_boy_sad(c, cx, cy, size):
    """Can-boy sitting down with a broken heart over his head -- 0.51b's
    camera-denied illustration.

    Sitting is carried by the legs alone: splayed forward from the hip to
    feet resting on an implied floor, against the standing pose's two
    straight drops. A front-facing figure has no other way to say "sitting"
    -- there is no profile to bend at the waist -- and the low, wide
    silhouette is what makes it read as deflated rather than just idle.
    Both arms hang instead of one on the hip; a hand on the hip is a
    confident pose and fights the rest of it.

    The heart sits off-centre to his left. Centred, it collided with the
    pull tab, which is not a piece of the mark worth moving for a prop.
    """
    g = size / 100.0
    c.add(f'<g transform="translate({cx - size/2:.2f} {cy - size/2:.2f}) scale({g:.4f})">')
    c.add(f'<circle cx="50" cy="50" r="50" fill="{wf.BRAND_MARK}"/>')

    # 0.74 and pushed down 5: sitting drops the body's mass into the lower
    # half of the disc, and the heart needs headroom above the lid that the
    # standing pose spends on legs.
    c.add('<g transform="translate(50 55) scale(0.74) translate(-50 -50)">')
    c.add('<g fill="none" stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round">')

    # Arms tucked close to the body and stopping well short of the legs. A
    # first pass hung them in a wide sweep that paralleled the splayed legs,
    # and four limbs of the same length fanning off one body read as a
    # spider, not a slump. Legs long and near-horizontal, arms short and
    # near-vertical: the contrast is what keeps them separate at size.
    c.add('<g stroke-width="4.2">')
    # The limbs are drawn *under* the can, so an arm tucked against the body
    # is simply painted over by the 5.2-wide body outline and vanishes. Like
    # can_boy's own hip arm (which reaches out to x=17), these have to clear
    # the silhouette to exist at all.
    c.add('<path d="M31 44 Q21 53 20 66"/>')          # left arm, limp
    c.add('<path d="M69 44 Q79 53 80 66"/>')          # right arm, limp
    c.add('<path d="M42 76 Q32 90 19 90"/>')          # left leg, out front
    c.add('<path d="M58 76 Q68 90 81 90"/>')          # right leg, out front
    c.add('</g>')

    c.add('<g stroke-width="5.2">')
    c.add('<path d="M33 27 C 29 41, 29 60, 33 74 C 40 78, 60 78, 67 74 '
          'C 71 60, 71 41, 67 27"/>')
    c.add('<ellipse cx="50" cy="24" rx="19" ry="6.5"/>')
    c.add('</g>')
    c.add('<g transform="translate(58 12) rotate(-12)" stroke-width="3">')
    c.add('<ellipse cx="0" cy="0" rx="5.4" ry="3.6"/>')
    c.add('<path d="M0 3.6 L-0.8 7.6"/>')
    c.add('</g>')

    # The broken heart: two half outlines tilted apart about the point where
    # they used to meet, each closed by its own zigzag along the break. The
    # zigzag is the whole trick -- two smooth half-lobes tilted apart read as
    # a pair of leaves, and at this size a fracture drawn as a thin gap
    # between them disappears entirely.
    c.add('<g transform="translate(38 -1) scale(1.3)" stroke-width="2.2">')
    c.add('<g transform="translate(-1.3 0) rotate(-15 0 6)">'
          '<path d="M0 -3.2 C0 -5.2 -1.8 -7.6 -4.5 -6.5 C-8 -5 -7 0 0 6 '
          'L-1.6 3.2 L1 1 L-1.2 -1.2 Z"/></g>')
    c.add('<g transform="translate(1.3 0) rotate(15 0 6)">'
          '<path d="M0 -3.2 C0 -5.2 1.8 -7.6 4.5 -6.5 C8 -5 7 0 0 6 '
          'L1.6 3.2 L-1 1 L1.2 -1.2 Z"/></g>')
    c.add('</g>')

    c.add('</g>')      # stroke group
    c.add('<g transform="translate(50 57) scale(0.5) translate(-63.54 -50.33)" '
          'fill="#FFFFFF">' + "".join(wf._LOGO_WORD) + '</g>')
    c.add('</g>')      # shrink
    c.add('</g>')


def can_boy_v60(c, cx, cy, size, tilt=0.0):
    """Can-boy brewing pour-over -- the empty Sessions block on a bean page
    with nothing logged yet ("no brews yet, go brew one").

    `tilt` adds degrees to the kettle's resting 30deg pour angle, pivoting it
    about the grip so the hand stays put and only the pot rolls; the stream's
    origin is recomputed from the rotated spout tip, so it never detaches. It
    rests at 0 and the still frame is the deliverable -- nothing drives it yet.

    THE RAISED ARM IS can_boy()'s BEAN ARM, VERBATIM: "M70 38 Q81 29 79 16" is
    the same curve, and the kettle's grip sits exactly on (79, 16), the point
    where can_boy() puts the bean. Swap the prop, keep the pose. That is not a
    stylistic nicety -- an earlier pass drew a flatter arm to keep the forearm
    off the pot, and because limbs are drawn UNDER the can, the body outline's
    5.2 stroke swallowed it: clearance at mid-arm measured 0.2 units against
    the bean arm's 3.5, so what rendered was a kettle floating in the green
    with nothing joining it to can-boy. can_boy_sad()'s docstring warns about
    exactly this. The arm connecting mascot to prop is the whole illustration;
    if the kettle has to move to keep that arm, the kettle moves.

    Everything else of can-boy is verbatim too -- hip arm, both legs, can body,
    lid ellipse, pull tab, belly wordmark -- except that he slides 15 units
    LEFT inside the composition. can_boy_camera() does the same for one camera;
    a whole brew bar needs it more, and it clears the right third of the disc
    for the prop column at x~77..105.

    What pays for three props is the shrink group's ANCHOR: (56.4, 57.9), the
    centre of the artwork's own minimum enclosing circle, not (50, 50). Aiming
    the disc at the content rather than at the coordinate origin is worth so
    much radius that the shrink still lands at 0.81, within a point of
    can_boy()'s 0.82, so the mascot reads the same size as in his other poses.
    Do not "simplify" that anchor back to (50, 50) -- at this scale it throws
    the server off the disc.

    Measured, not eyeballed, by rasterizing and testing every white pixel: the
    ink's enclosing circle is concentric with the disc to within 0.03 units and
    clears the edge by 8.2%. Four different things sit on that circle at once
    -- the spout's hook (97.4, 18.9), the server's bottom-right corner (103.5,
    89.4), the hip hand (-0.1, 54.5) and the can's lid (14.7, 20.4) -- so there
    is no slack left anywhere: moving any one of them outward costs scale off
    the whole figure.

    The kettle is the piece that fought back, and the constraint is a LEVER:
    the hand grips the handle, so grip-to-spout-tip is a rigid arm, and the tip
    has to land over the cone. Lengthen the spout or deepen the handle and the
    tip swings right, dragging the cone and the server right with it until the
    disc runs out. Three passes failed on this. A bail handle shortens the
    lever but hangs the pot directly under the hand, where the arm crosses it,
    and its arc continued the line of the arm so the two read as one hook. A
    big bellied body with an ellipse lid turns, at any real pour angle, into a
    diagonal oval that reads as an opening rather than a lid. And a spout whose
    limbs are both vertical is a hairpin -- it reads as a wire handle on the
    wrong side of the pot.

    What works: a flat-topped body (the flat top is what survives being rotated
    30deg, which an ellipse does not), a small trapezoid lid cap instead of a
    lid ellipse, a shallow side handle, and a neck that leaves the body LOW and
    climbs on a long diagonal before hooking over. That puts the tip at
    (93.2, 25.4), on the cone's centreline, with the hand still on the bean
    arm's own endpoint.

    The cone is hario-v60.svg's own construction -- rim ellipse, two ribs, the
    bottom ellipse, the spiral rib -- dropped in through the icon's own
    coordinate frame at 12.5/26, so this cone and the ones in the Sessions rows
    are literally the same drawing. Stroke widths inside that group are
    pre-divided by the same factor so they come out at this figure's prop
    weights (3.0 silhouette, 2.0 detail) instead of a 5.5 slab.

    The server's handle faces LEFT, toward can-boy, not right. A right-facing
    handle is the more common product photo, but the server's bottom-right
    corner is already one of the four points pinning the enclosing circle, so
    an arc out that side would have cost the whole figure scale; facing left it
    fills the otherwise dead pocket under the pour instead.

    No steam. The pour stream already occupies the only air between spout and
    rim, and short strokes stacked in there read as spatter, not heat.
    """
    g = size / 100.0
    c.add(f'<g transform="translate({cx - size/2:.2f} {cy - size/2:.2f}) scale({g:.4f})">')
    c.add(f'<circle cx="50" cy="50" r="50" fill="{wf.BRAND_MARK}"/>')

    # where the hand closes on the kettle handle, in figure space, and the
    # handle's own outer mid in kettle-local space -- the pot is rotated about
    # the pair, so `tilt` rolls the kettle inside a fixed grip
    GX, GY = 64.0, 16.0
    HX, HY = -12.5, 1.0
    ANG = 30.0 + tilt
    # spout tip in kettle-local space, and the cone's mouth
    TX, TY = 17.5, -5.5
    CONE_X, CONE_TOP, CONE_R = 93.0, 47.0, 12.5

    c.add('<g transform="translate(50 50) scale(0.81) translate(-56.4 -57.9)">')
    c.add('<g fill="none" stroke="#FFFFFF" stroke-linecap="round" stroke-linejoin="round">')

    # ---- can-boy, slid 15 left; everything inside is can_boy()'s own frame --
    c.add('<g transform="translate(-15 0)">')
    c.add('<g stroke-width="4.2">')
    c.add('<path d="M30 40 Q19 44 17 55"/>')   # right arm, hand on hip
    c.add('<path d="M41 75 L37 90"/>')          # left leg
    c.add('<path d="M59 75 L63 90"/>')          # right leg
    # pouring arm: can_boy()'s own bean arm, unchanged (see docstring)
    c.add('<path d="M70 38 Q81 29 79 16"/>')
    c.add('</g>')
    c.add('<g stroke-width="5.2">')
    c.add('<path d="M33 27 C 29 41, 29 60, 33 74 C 40 78, 60 78, 67 74 '
          'C 71 60, 71 41, 67 27"/>')
    c.add('<ellipse cx="50" cy="24" rx="19" ry="6.5"/>')
    c.add('</g>')
    c.add('<g transform="translate(58 12) rotate(-12)" stroke-width="3">')
    c.add('<ellipse cx="0" cy="0" rx="5.4" ry="3.6"/>')
    c.add('<path d="M0 3.6 L-0.8 7.6"/>')
    c.add('</g>')
    c.add('</g>')

    # ---- gooseneck kettle -------------------------------------------------
    # Squat body + a lid ellipse deliberately shaped like the can's own lid,
    # so the prop is built out of the mark's vocabulary. The neck is a single
    # unclosed stroke: at this size a two-sided tube fills in solid, and one
    # swan curve is the whole reason the pot reads as "pour-over kettle"
    # rather than "teapot".
    c.add(f'<g transform="translate({GX} {GY}) rotate({ANG:.2f}) '
          f'translate({-HX} {-HY})">')
    c.add('<g stroke-width="3.2">')
    # closed, bellied body with a FLAT top -- the flat top is the whole reason
    # the pot reads at 30deg; an ellipse lid in a rotated frame turns into a
    # diagonal oval that reads as an opening, not a lid.
    c.add('<path d="M-9 -6 L9 -6 C 10.8 0.5, 8 9.5, 0 9.5 '
          'C -8 9.5, -10.8 0.5, -9 -6 Z"/>')
    # gooseneck. It leaves the body LOW and climbs on a long diagonal before
    # the hook: a neck whose two limbs are both vertical is a hairpin and
    # reads as a wire handle, which is what the first two passes drew.
    c.add('<path d="M8.3 4 C 13.5 2.5, 15.5 -3, 15 -9 '
          'C 14.8 -12.8, 18.8 -13, 18.2 -9 L17.5 -5.5"/>')
    c.add('</g>')
    c.add('<g stroke-width="2.6">')
    c.add('<path d="M-4 -6 L-3.4 -9.4 L3.4 -9.4 L4 -6"/>')              # lid
    # side handle, facing can-boy. Short and shallow on purpose: the loop is
    # a lever between the hand and the spout tip, and every unit of depth
    # here pushes the tip further right than the cone can follow.
    c.add('<path d="M-9.4 -3 Q-12.5 -3.5 -12.5 1 Q-12.5 5.5 -9.4 6"/>')
    c.add('</g>')
    c.add('</g>')

    # ---- the pour ---------------------------------------------------------
    # Where the spout tip actually ended up after the rotation, so the stream
    # starts on the lip at any `tilt` instead of near it. It bows the way a
    # falling stream does -- angled off the spout, vertical by the time it
    # lands -- and finishes at y=44.5, just past the rim ellipse's own back
    # edge at 44.1, so it reads as going INTO the cone rather than stopping
    # short above it.
    a = math.radians(ANG)
    tx = GX + (TX - HX) * math.cos(a) - (TY - HY) * math.sin(a)
    ty = GY + (TX - HX) * math.sin(a) + (TY - HY) * math.cos(a)
    ey = CONE_TOP - 2.5
    c.add(f'<path d="M{tx:.2f} {ty:.2f} Q{CONE_X + (tx - CONE_X) * 0.25:.2f} '
          f'{ty + (ey - ty) * 0.55:.2f} {CONE_X:.2f} {ey:.2f}" stroke-width="2.2"/>')

    # ---- V60, hario-v60.svg's own paths in the icon's coordinate frame ----
    s = CONE_R / 26.0    # the icon draws its rim at rx=26, cx=50, cy=30
    c.add(f'<g transform="translate({CONE_X} {CONE_TOP}) scale({s:.4f}) '
          f'translate(-50 -30)">')
    c.add(f'<g stroke-width="{3.0 / s:.2f}">')
    c.add('<ellipse cx="50" cy="30" rx="26" ry="6"/>')
    c.add('<path d="M24 30 L45 82"/>')
    c.add('<path d="M76 30 L55 82"/>')
    c.add('</g>')
    c.add(f'<ellipse cx="50" cy="82" rx="5" ry="2.6" stroke-width="{2.0 / s:.2f}"/>')
    # the spiral, but only its top three sweeps: the icon runs it all the way
    # to the drip hole, and at half the icon's size those last two turns land
    # inside 5 units of cone and silt up into a grey smudge. Stopping it at
    # the widest, most legible part keeps the one cue that says "V60".
    c.add('<path d="M32 38 Q50 44 68 40 Q52 52 36 50 Q52 62 64 56" '
          f'stroke-width="{2.0 / s:.2f}"/>')
    c.add('</g>')

    # ---- server ------------------------------------------------------------
    # Mouth drawn wider than the body, so the cone reads as sitting IN it and
    # not balanced on a jar. Bottom corners rounded rather than square: this
    # corner is one of the four points pinning the enclosing circle, so the
    # radius the round corner saves comes straight off the whole figure.
    c.add('<g stroke-width="2.8">')
    c.add('<path d="M81 75 L105 75"/>')
    c.add('<path d="M82.5 75 L82.5 84.5 Q82.5 91 89 91 L97 91 '
          'Q103.5 91 103.5 84.5 L103.5 75"/>')
    c.add('</g>')
    c.add('<path d="M82.5 78.5 Q77 79 77.5 83.5 Q78 87 82.5 87" '
          'stroke-width="2.4"/>')

    c.add('</g>')      # stroke group
    c.add('<g transform="translate(-15 0)">'
          '<g transform="translate(50 57) scale(0.5) translate(-63.54 -50.33)" '
          'fill="#FFFFFF">' + "".join(wf._LOGO_WORD) + '</g></g>')
    c.add('</g>')      # composition
    c.add('</g>')


# ------------------------------------------------------------- -1w intro ----
def can_drink_intro(bean_angle=0.0):
    """First run of the Can Drink page (swipe left from Home)."""
    c = wf.Canvas("Can Drink · intro — scheme E")
    wf.status_bar(c)
    can_boy(c, 180, 208, 195, bean_angle=bean_angle)
    wf.text(c, 180, 424, "What's good", "headlineMedium", wf.C["onSurface"],
            "middle", family=HEADLINE, size=33)
    wf.text(c, 180, 460, "right now", "headlineMedium", wf.C["onSurface"],
            "middle", family=HEADLINE, size=33)
    for i, ln in enumerate(("Fresh arrivals from specialty roasters —",
                            "new origins, processes and prices,",
                            "gathered in one place.")):
        wf.text(c, 180, 504 + i * 24, ln, "bodyLarge", wf.C["onSurfaceVariant"],
                "middle")
    wf.button(c, 68, 636, 224, "Start")
    wf.text(c, 180, 716, "Swipe right to go back to your beans", "labelMedium",
            wf.C["outline"], "middle")
    wf.gesture_bar(c)
    return c


# --------------------------------------------------------------- -1 drink ---
# The real Can Drink catalogue -- where "Start" on the -1w intro lands. Same
# card pattern as wireframes.catalogue() (the pre-scheme-e sketch of this
# page, still rendered per-variant via PAGES in that file), just restyled
# through scheme E's tokens/type and, per the brief, showing six roasters'
# beans instead of four -- picked at random from a larger pool each run, the
# way the real app would rotate what's featured.
_BEAN_POOL = (
    ("Kenya AA Karatu", "Lomi · Kenya", "€16 · 250 g", True, True),
    ("Panama Geisha", "Tanat · Panama", "€42 · 100 g", False, True),
    ("Brazil Cerrado", "Coutume · Brazil", "€13 · 250 g", False, False),
    ("Guatemala Huehue", "Belleville · Guatemala", "€15 · 250 g", False, True),
    ("Ethiopia Guji", "Terres de Café · Ethiopia", "€17 · 250 g", True, True),
    ("Colombia Pink Bourbon", "La Cabra · Colombia", "€19 · 250 g", False, True),
    ("Rwanda Nyungwe", "Café Lomi · Rwanda", "€14 · 250 g", False, False),
    ("Yemen Haraaz", "Cafés Méo · Yemen", "€38 · 100 g", True, True),
    ("Honduras Marcala", "Hexagon · Honduras", "€12 · 250 g", False, True),
    ("Costa Rica Tarrazú", "Dak · Costa Rica", "€16 · 250 g", False, True),
)


def can_drink(seed=11):
    """The Can Drink catalogue, six beans deep. `seed` pins the random six
    for a reproducible build; drop it for a genuinely different six each run."""
    c = wf.Canvas("Can Drink — scheme E")
    wf.status_bar(c)
    wf.top_bar(c, "Can Drink", back=True, actions=("sort",))
    wf.rect(c, wf.GUTTER, 104, W - 2 * wf.GUTTER, 56, wf.C["surfaceContainer"], 28)
    wf.circle(c, 44, 132, 8, "none", stroke=wf.C["onSurfaceVariant"], sw=2)
    wf.line(c, 50, 138, 56, 144, wf.C["onSurfaceVariant"], 2)
    wf.text(c, 72, 138, "Search roasters and beans", "bodyLarge", wf.C["onSurfaceVariant"])
    x = wf.chip(c, wf.GUTTER, 168, "In stock", selected=True)
    x = wf.chip(c, x, 168, "Roaster", menu=True)
    wf.chip(c, x, 168, "Origin", menu=True)

    beans = random.Random(seed).sample(_BEAN_POOL, 6)
    wf.text(c, 20, 236, f"Newest first · {len(_BEAN_POOL) * 7} beans", "labelMedium",
            wf.C["onSurfaceVariant"])

    card_h, photo_h, row_gap = 164, 84, 12
    for i, (name, roaster, price, new, stock) in enumerate(beans):
        cx = wf.GUTTER + (i % 2) * 168
        cy = 248 + (i // 2) * (card_h + row_gap)
        wf.card(c, cy, card_h, x=cx, w=152)
        wf.photo(c, cx, cy, 152, photo_h, r=wf.R_LG)
        wf.rect(c, cx, cy + photo_h - 16, 152, 16, wf.C["cardSurface"])
        if new:
            wf.rect(c, cx + 10, cy + 8, 42, 18, wf.C["tertiary"], 9)
            wf.text(c, cx + 31, cy + 21, "New", "labelSmall", wf.C["onTertiary"], "middle")
        wf.text(c, cx + 12, cy + 100, name, "titleMedium", size=13)
        wf.text(c, cx + 12, cy + 116, roaster, "bodyMedium", wf.C["onSurfaceVariant"], size=11)
        wf.text(c, cx + 12, cy + 132, price, "bodyMedium", wf.C["onSurfaceVariant"], size=11)
        if stock:
            wf.rect(c, cx + 12, cy + 140, 66, 16, wf.C["primaryContainer"], wf.R_XS)
            wf.text(c, cx + 45, cy + 152, "In stock", "labelSmall",
                    wf.C["onPrimaryContainer"], "middle")
        else:
            wf.rect(c, cx + 12, cy + 140, 74, 16, wf.C["surfaceContainer"], wf.R_XS)
            wf.text(c, cx + 49, cy + 152, "Sold out", "labelSmall",
                    wf.C["onSurfaceVariant"], "middle")
        wf.ext_link(c, cx + 128, cy + 141)
    wf.gesture_bar(c)
    return c


# ----------------------------------------------------------------- +1 sessions
def sessions():
    """+1: every brew session across every bean, sorted by date (newest
    first) -- the chronological counterpart to Home's per-bean grouping.

    Reuses bean_detail_lower's own session-row convention (wireframes.py:
    date, method, dose, score and an extraction word on one compact line, a
    hairline divider, no card chrome) rather than -1_can_drink/Home's card
    treatment: a log is denser and more numerous than a shelf of beans or
    products, and card chrome per row would fight that density.

    Session counts per bean here match home()'s sample brew_count values
    (Ethiopia 4, Colombia 2, Guatemala 1, Kenya 0) so the two pages agree.

    The leading circle is the dripper, not the bean: bean identity is
    already fully spelled out as the row's own title text, so a second,
    abbreviated repeat of it (initials in a monogram) would be redundant.
    Method is the thing the title text *doesn't* already say, and the one a
    dripper_icons/ figure (see dripper_icon() above) actually helps to
    scan for -- "V60" only means something to someone who already knows
    what a V60 looks like, and several rows in a row using the same
    dripper become a recognisable silhouette repeating, not five separate
    words to re-read. The circle itself switches from the old monogram's
    pale secondaryContainer to BRAND: the icon is white-only linework
    (dripper_icon()'s own recipe), and secondaryContainer is pale enough
    that white on it is close to invisible -- BRAND is the same green
    can_boy()/bag_tile() already stand their own white linework on.
    """
    log = [
        ("30 Jul", "Ethiopia Guji Natural", "V60", "15.0 g", 4.5, "well extracted"),
        ("25 Jul", "Ethiopia Guji Natural", "Kalita", "16.0 g", 4.0, "slightly under"),
        ("22 Jul", "Colombia Huila Washed", "V60", "15.5 g", 3.5, "slightly over"),
        ("18 Jul", "Ethiopia Guji Natural", "V60", "15.0 g", 4.0, "well extracted"),
        ("15 Jul", "Guatemala Huehue", "V60", "15.0 g", 3.0, "slightly under"),
        ("12 Jul", "Ethiopia Guji Natural", "Chemex", "20.0 g", 4.5, "well extracted"),
        ("08 Jul", "Colombia Huila Washed", "Kalita", "16.0 g", 4.0, "well extracted"),
    ]
    c = wf.Canvas("Sessions — scheme E")
    wf.status_bar(c)
    wf.top_bar(c, "Sessions", back=True, actions=("sort",))
    wf.text(c, 20, 112, f"Newest first · {len(log)} sessions", "labelMedium",
            wf.C["onSurfaceVariant"])

    row_h, row_gap, y0 = 64, 4, 132
    for i, (date, bean, dripper, dose, score, note) in enumerate(log):
        ry = y0 + i * (row_h + row_gap)
        # BRAND, not secondaryContainer: the icons are white-only linework
        # (dripper_icon()/can_boy()/bag_tile()'s shared recipe), and
        # secondaryContainer (#E3F6E3) is pale enough that white on it is
        # nearly invisible -- the same green can_boy/bag_tile stand on
        wf.circle(c, wf.GUTTER + 20, ry + 24, 20, BRAND)
        if not dripper_icon(c, wf.GUTTER + 20, ry + 24, 26, dripper):
            wf.text(c, wf.GUTTER + 20, ry + 29, dripper[:2].upper(), "titleSmall",
                    "#FFFFFF", "middle")
        tx = wf.GUTTER + 52
        wf.text(c, tx, ry + 20, bean, "titleMedium", size=14)
        wf.text(c, W - wf.GUTTER - 24, ry + 20, date, "bodyMedium",
                wf.C["onSurfaceVariant"], "end", size=12)
        wf.text(c, tx, ry + 40, f"{dripper} · {dose} · {score:.1f} · {note}",
                "bodyMedium", wf.C["onSurfaceVariant"], size=12)
        wf.path(c, f"M{W-wf.GUTTER-14} {ry+19} l5 5 l-5 5", stroke=wf.C["outline"], sw=1.6)
        if i < len(log) - 1:
            wf.line(c, tx, ry + row_h - 8, W - wf.GUTTER, ry + row_h - 8)

    # FAB, clear of the last row -- logs a new session
    fab_cy = y0 + len(log) * (row_h + row_gap) + 32
    wf.circle(c, 312, fab_cy, 28, wf.C["primary"], stroke=wf.C.get("primaryOutline"))
    wf.path(c, f"M300 {fab_cy} h24 M312 {fab_cy - 12} v24", stroke=wf.C["onPrimary"], sw=2.6)
    wf.gesture_bar(c)
    return c


# ----------------------------------------------------------------- +2 profile
# 09 (wireframes.profile) brought onto the swipe axis at +2, and split into the
# two states it always implied but never drew: signed out and signed in.
#
# Splitting it is what took the avatar out of Home's top bar. That avatar was
# the only way in to this page, and an avatar is by definition a signed-in
# artifact -- 00_home_empty is a phone nobody has logged into yet, so it was
# drawing a face for a user who does not exist. Reaching profile by swiping
# right twice costs nothing and works in both states.
#
# NOTE, and it is not a design note: specs/legal-android.md rule 16 says that
# the moment this app grows an account, Play's Account Deletion policy
# activates and the in-app deletion path plus a public web deletion URL have
# to ship *with* the account feature, not after it. So the signed-in state
# carries a "Delete account" row. It is the reason its list is titled
# "Account & legal" where the signed-out one is still "About & legal": with no
# account there is nothing to delete, and the version row keeps that slot.
def _about_card(c, y, rows):
    """The legal list both profile states carry, unchanged from 09 except that
    the row set is now a parameter -- the two states need different last rows.

    `rows` is a sequence of (label, sub, kind); `kind` is "chevron" (navigates,
    optional second line), "value" (`sub` printed right-aligned, no chevron) or
    "danger" (chevron, error ink).
    """
    h = len(rows) * 58
    wf.card(c, y, h)
    for i, (lab, sub, kind) in enumerate(rows):
        ry = y + i * 58
        two = sub is not None and kind != "value"
        ink = wf.C["error"] if kind == "danger" else wf.C["onSurface"]
        wf.text(c, 32, ry + (28 if two else 34), lab, "bodyLarge", ink)
        if two:
            wf.text(c, 32, ry + 46, sub, "bodyMedium", wf.C["onSurfaceVariant"])
        if kind == "value":
            wf.text(c, 328, ry + 34, sub, "bodyMedium", wf.C["onSurfaceVariant"], "end")
        else:
            wf.path(c, f"M322 {ry+27} l6 6 l-6 6",
                    stroke=ink if kind == "danger" else wf.C["outline"], sw=1.6)
        if i < len(rows) - 1:
            wf.line(c, 32, ry + 58, 332, ry + 58)
    return y + h


def profile_empty():
    """+2 signed out: no avatar, no name, no email, because none of the three
    exist yet.

    09 opens with an avatar over a Change photo button over two filled fields.
    All four are *your* data, so with nobody logged in there is nothing to draw
    and no honest placeholder to draw instead -- a grey ring where a face goes
    is the same lie as a radar polygon at zero. They collapse into one block:
    the mark, what the app does with your data today, and the way in.

    The mark, not can-boy. can_boy_sad() carries 0.51b because a denied camera
    permission is a small disappointment aimed at the user; not being logged in
    is not a disappointment, it is the default, and a mascot pulling a face
    about it would be asking for something the copy should just offer.

    The copy leads with what is true right now -- the log is on this phone and
    works fine without an account -- because the alternative reads as a wall
    asking you to sign up before you can see your own coffee. Logging in is the
    addition, so it is the second sentence.
    """
    c = wf.Canvas("Profile · signed out — scheme E (+2)")
    wf.status_bar(c)
    wf.top_bar(c, "Profile", back=True)

    wf.logo(c, 180, 176, 88)
    wf.text(c, 180, 256, "Not signed in", "headlineMedium", wf.C["onSurface"],
            "middle", family=HEADLINE, size=30)
    for i, ln in enumerate(("Your beans and sessions live on this",
                            "phone and work without an account. Log",
                            "in to sync them across your devices.")):
        wf.text(c, 180, 288 + i * 22, ln, "bodyLarge", wf.C["onSurfaceVariant"],
                "middle")
    wf.button(c, 68, 362, 224, "Log in")
    wf.button(c, 68, 410, 224, "Create an account", "text")

    wf.section(c, 496, "About & legal")
    _about_card(c, 510, (("Privacy Policy", None, "chevron"),
                         ("How we use AI", "Re-read the disclosure", "chevron"),
                         ("Open-source licences", None, "chevron"),
                         ("Version", "1.0.0 (14)", "value")))
    wf.gesture_bar(c)
    return c


def google_g(c, cx, cy, size):
    """Google's four-colour "G", drawn as a ring in four arcs plus the bar.

    Approximated, not the official asset: a wireframe cannot ship Google's
    artwork, and this is a stand-in for the real mark at the size and position
    it occupies. specs/legal-accounts.md is explicit that the shipping build
    must use the unmodified full-colour asset -- scaled only with aspect ratio
    preserved, never monochrome, never redrawn. So do not treat this figure as
    a spec for anything but layout.
    """
    r, sw = size * 0.36, size * 0.24
    # The gap runs 0..25deg, where the crossbar exits. Closing it any further
    # turns the mark into a pinwheel -- measured in the raster, not guessed.
    arcs = (("#4285F4", 315, 360), ("#EA4335", 225, 315),
            ("#FBBC05", 160, 225), ("#34A853", 25, 160))
    for col, a1, a2 in arcs:
        p1, p2 = math.radians(a1), math.radians(a2)
        la = 1 if (a2 - a1) > 180 else 0
        c.add(f'<path d="M{cx + r * math.cos(p1):.2f} {cy + r * math.sin(p1):.2f} '
              f'A{r:.2f} {r:.2f} 0 {la} 1 '
              f'{cx + r * math.cos(p2):.2f} {cy + r * math.sin(p2):.2f}" '
              f'fill="none" stroke="{col}" stroke-width="{sw:.2f}"/>')
    # the crossbar, blue, running out through the ring's gap at 3 o'clock
    c.add(f'<path d="M{cx - r * 0.05:.2f} {cy:.2f} L{cx + r + sw / 2:.2f} {cy:.2f}" '
          f'fill="none" stroke="#4285F4" stroke-width="{sw * 0.85:.2f}"/>')


# --------------------------------------------------------- +2.1 create account
# Reached from +2_profile_empty's "Create an account", the same way 0.51 is
# reached from 0.5's scan prompt.
#
# Every element on this page is here because specs/legal-accounts.md's UI
# section puts it here, and a few things are conspicuously absent for the same
# reason. The short version, with the rule each one answers:
#
#   Google button first, email second, both the same width and height, no
#   primary/secondary styling between them   -- they are equivalent options,
#   and neither store permits one to be buried behind "more options".
#
#   The Google button keeps Google's own colours and its own typeface, not
#   scheme E's. It is the one control on any page in this deck that the design
#   system does not get to touch: the exact fill/stroke/ink values are a
#   condition of Google's app verification, not a style preference. It looks
#   foreign on this page on purpose.
#
#   Two separate data statements, not one. "We only collect your name and
#   email" is the natural thing to write here and it is false the moment sync
#   exists -- beans, brews and photos upload too, and a sign-up screen that
#   contradicts the store data declarations is a problem in both consoles.
#
#   Terms and Privacy links, tappable from this screen.
#
#   An age affirmation at 13+, drawn UNTICKED. Pre-ticked consent is not
#   consent. No date of birth is collected -- the checkbox is the whole ask.
#
# Absent on purpose, and it would be a defect to add them: any AI-processing
# consent (that is a separate screen at first AI use, and must never be
# bundled into sign-up), a phone number, a birthday, a display name, an
# avatar, and any marketing opt-in as a condition of creating the account.
#
# This is the ANDROID variant: two methods. The iOS variant is a different
# screen -- Apple's Guideline 4.8 puts Sign in with Apple on it as a third
# button, first in the stack -- and is not drawn here, because this deck is
# coffee_android and has no iOS pages at all. It still has to exist before
# iOS submission.
def create_account():
    """+2.1: the create-account form, reached from +2_profile_empty.

    The page leads with the two sign-up methods rather than the form, because
    the form is the slower of the two and putting it first reads as "fill this
    in, or, if you like, don't". Google's button and the email form are the
    same width for the same reason -- neither is the recommended path.

    Nothing on this page is required to use the app. That is the point of the
    "You can keep using Coffee Can without an account" line at the foot: the
    account buys sync and nothing else, and both stores take a dim view of a
    sign-up wall in front of functionality that works offline. 00_home and
    every bean page render with no account at all, which is what makes that
    line true rather than reassuring.
    """
    c = wf.Canvas("Create account — scheme E (+2.1)")
    wf.status_bar(c)
    wf.top_bar(c, "Create account", back=True)

    # --- Google, drawn to Google's spec, not scheme E's -------------------
    # Light theme: #FFFFFF fill, #747775 stroke, #1F1F1F ink. The app's green
    # tokens do not apply here and the corner radius follows this deck only
    # because Google permits scaling, not because it may be restyled.
    wf.rect(c, wf.GUTTER, 116, W - 2 * wf.GUTTER, 48, "#FFFFFF", 24,
            stroke="#747775")
    google_g(c, 62, 140, 22)
    wf.text(c, 190, 145, "Sign up with Google", "labelLarge", "#1F1F1F", "middle",
            family="'Liberation Sans',sans-serif", size=15)

    # 184, not 186: the Email field's floating label notch starts at 206, and
    # at 186 the rules ran into the top of it
    wf.line(c, 20, 184, 158, 184)
    wf.text(c, 180, 189, "or", "labelMedium", wf.C["onSurfaceVariant"], "middle")
    wf.line(c, 202, 184, 340, 184)

    # --- the app's own email account --------------------------------------
    wf.textfield(c, wf.GUTTER, 212, W - 2 * wf.GUTTER, "Email", "raul@example.com")
    # a space, not "", so textfield() doesn't fall back to its em-dash empty
    # marker -- the dots below stand in for the masked value
    wf.textfield(c, wf.GUTTER, 284, W - 2 * wf.GUTTER, "Password", " ")
    for i in range(8):
        wf.circle(c, 36 + i * 11, 315, 2.6, wf.C["onSurface"])
    wf.text(c, 20, 356, "At least 8 characters", "labelSmall",
            wf.C["onSurfaceVariant"])

    # --- age affirmation, unticked ----------------------------------------
    wf.rect(c, 20, 374, 20, 20, "none", wf.R_XS, stroke=wf.C["outline"], sw=1.6)
    wf.text(c, 52, 389, "I'm 13 or older", "bodyMedium", wf.C["onSurface"])

    # --- terms + privacy, both reachable from this screen ------------------
    wf.text(c, 20, 420, "By creating an account you agree to the", "bodyMedium",
            wf.C["onSurfaceVariant"], size=13)
    wf.text(c, 20, 440, "Terms of service", "bodyMedium", wf.C["primaryText"], size=13)
    wf.text(c, 124, 440, "and", "bodyMedium", wf.C["onSurfaceVariant"], size=13)
    wf.text(c, 152, 440, "Privacy policy.", "bodyMedium", wf.C["primaryText"], size=13)

    # --- what the account holds, and what syncing sends --------------------
    wf.rect(c, wf.GUTTER, 464, W - 2 * wf.GUTTER, 78, wf.C["surfaceContainer"], wf.R_MD)
    for i, ln in enumerate(("Your account stores your email address.",
                            "Syncing uploads your beans, brews and photos",
                            "so they appear on your other devices.")):
        wf.text(c, 28, 488 + i * 19, ln, "bodyMedium", wf.C["onSurfaceVariant"],
                size=13)

    wf.button(c, wf.GUTTER, 562, W - 2 * wf.GUTTER, "Create account")

    wf.text(c, 180, 646, "Already have an account?", "bodyMedium",
            wf.C["onSurfaceVariant"], "middle")
    wf.text(c, 180, 670, "Log in", "labelLarge", wf.C["primaryText"], "middle")

    wf.text(c, 180, 736, "You can keep using Coffee Can", "labelSmall",
            wf.C["outline"], "middle")
    wf.text(c, 180, 754, "without an account.", "labelSmall", wf.C["outline"],
            "middle")
    wf.gesture_bar(c)
    return c


def profile():
    """+2 signed in: 09's avatar, Change photo, Name and Email, with the two
    additions the signed-out twin makes necessary.

    "Log out" sits in the top bar's right action slot as words rather than a
    glyph -- there is no icon for logging out that half the world doesn't read
    as "log in", and top_bar()'s glyph vocabulary (avatar, share, close, sort)
    has nothing close. It stays primaryText rather than error ink: logging out
    is reversible and does not touch data, and spending the error colour here
    would leave nothing louder for Delete account, which is neither.

    Delete account is in the list, not the top bar, and the version row moves
    down to the footer to make room for it -- see the section note above for
    why it is not optional. Its supporting line names what goes, because
    "Delete account" alone does not say whether the brews on this phone go
    with it.

    The name is Raul, not 09's Zixing, only so it agrees with the avatar letter
    scheme E already sets (wf.AVATAR = "R"). If the sample name changes, change
    the letter with it -- a face reading R above a field reading Zixing is the
    kind of detail a reviewer trips on and then distrusts the rest of the page.
    """
    c = wf.Canvas("Profile · signed in — scheme E (+2)")
    wf.status_bar(c)
    wf.top_bar(c, "Profile", back=True)
    wf.text(c, W - 20, 61, "Log out", "labelLarge", wf.C["primaryText"], "end")

    wf.circle(c, 180, 168, 44, wf.C["secondaryContainer"])
    wf.text(c, 180, 182, wf.AVATAR, "displaySmall", wf.C["onSecondaryContainer"],
            "middle", family=HEADLINE)
    # 09's edit badge, verbatim -- it opens the photo picker. 09 built it by
    # drawing a tick and then string-replacing the path with a pencil; drawn
    # once here instead, same geometry.
    wf.circle(c, 210, 198, 18, wf.C["primary"], stroke=wf.C.get("primaryOutline"))
    wf.path(c, "M204 202 l7 -7 M204 202 v3 h3", stroke=wf.C["onPrimary"], sw=2)
    wf.button(c, 118, 224, 124, "Change photo", "text")

    wf.textfield(c, wf.GUTTER, 292, W - 2 * wf.GUTTER, "Name", "Raul")
    wf.textfield(c, wf.GUTTER, 364, W - 2 * wf.GUTTER, "Email", "raul@example.com")
    # 09 parks this at the very bottom of the page, where it reads as a footer
    # about the whole screen. It is only true of the two fields above it, so it
    # sits under them instead.
    wf.text(c, 20, 440, "Saved automatically", "labelSmall", wf.C["outline"])

    wf.section(c, 468, "Account & legal")
    _about_card(c, 482, (("Privacy Policy", None, "chevron"),
                         ("How we use AI", "Re-read the disclosure", "chevron"),
                         ("Open-source licences", None, "chevron"),
                         ("Delete account", "Removes the account and its synced data",
                          "danger")))
    wf.text(c, 20, 748, "Version 1.0.0 (14)", "labelSmall", wf.C["outline"])
    wf.gesture_bar(c)
    return c


PAGES = [("00w_welcome.svg", welcome),
         ("00_home.svg", home),
         ("00_home_empty.svg", home_empty),
         ("0.5_bean_profile.svg", bean_profile_empty),
         ("0.51_camera.svg", camera),
         ("0.51b_camera_permission.svg", camera_permission),
         ("0.6_bean_detail.svg", bean_detail),
         ("0.6b_bean_detail_lower.svg", bean_detail_lower),
         ("0.6_empty.svg", bean_detail_empty),
         ("0.6b_empty.svg", bean_detail_lower_empty),
         ("-1w_can_drink_intro.svg", can_drink_intro),
         ("-1_can_drink.svg", can_drink),
         ("+1_sessions.svg", sessions),
         ("+2_profile.svg", profile),
         ("+2_profile_empty.svg", profile_empty),
         ("+2.1_create_account.svg", create_account)]

# ----------------------------------------------------------------- motion ---
def _ease_out_cubic(t: float) -> float:
    return 1 - (1 - t) ** 3


def welcome_frames():
    """1s ease-out reveal, then hold."""
    n, ms, hold = 20, 50, 12
    fr = [(welcome(_ease_out_cubic(i / (n - 1))), ms) for i in range(n)]
    return fr + [(welcome(1.0), ms)] * hold


def home_empty_frames():
    """Idle attention wiggle on the CTA: a 600ms damped shake once every 3s.

    The rest of the cycle is two long-duration copies of the resting frame, so
    the GIF shows the true 3s cadence without carrying 60 redundant frames.
    """
    n, ms = 15, 40
    fr = []
    for i in range(n):
        t = i / (n - 1)
        fr.append((home_empty(shake=math.sin(2 * math.pi * 3 * t) * math.exp(-3.2 * t)),
                   ms))
    rest = home_empty()
    return fr + [(rest, 1200), (rest, 1200)]


def can_drink_intro_frames():
    """Can-boy shakes the held bean, a continuous ±15° rock rather than a
    one-off idle wiggle -- it's the page's whole reason for a GIF, not a
    background detail."""
    n, ms = 24, 60
    return [(can_drink_intro(bean_angle=15 * math.sin(2 * math.pi * i / n)), ms)
            for i in range(n)]


def bean_profile_frames():
    """The shutter beat on 0.5's hero: aim, press, flash, recoil, settle.

    Every knob is a continuous function of phase with f(1)=f(0), so the loop
    closes on its own -- see _win()."""
    n, ms = 24, 70
    return [(bean_profile_empty(i / n), ms) for i in range(n)]


MOTION = {"00w_welcome": welcome_frames, "00_home_empty": home_empty_frames,
          "-1w_can_drink_intro": can_drink_intro_frames,
          "0.5_bean_profile": bean_profile_frames}


def build_gif(name: str, frames_fn):
    """Render every frame in one browser pass as a grid, then slice it up."""
    from PIL import Image

    spec = frames_fn()
    cols = 6
    rows = -(-len(spec) // cols)
    cells = "".join(f'<div>{c.render()}</div>' for c, _ in spec)
    html = (f"<html><head><meta charset=utf-8><style>"
            f"*{{margin:0;padding:0;border:0}}"
            f"body{{display:grid;grid-template-columns:repeat({cols},{W}px);"
            f"width:{cols*W}px;background:#000}}"
            f"div{{width:{W}px;height:{H}px;overflow:hidden}}"
            f"svg{{width:{W}px;height:{H}px;display:block}}"
            f"</style></head><body>{cells}</body></html>")

    with tempfile.TemporaryDirectory() as td:
        page = pathlib.Path(td, "grid.html"); page.write_text(html)
        shot = pathlib.Path(td, "grid.png")
        subprocess.run(["google-chrome", "--headless", "--disable-gpu", "--no-sandbox",
                        "--hide-scrollbars", "--force-device-scale-factor=1",
                        f"--window-size={cols*W},{rows*H}",
                        f"--screenshot={shot}", str(page)],
                       check=True, capture_output=True)
        sheet = Image.open(shot).convert("RGB")
        frames = [sheet.crop(((i % cols) * W, (i // cols) * H,
                              (i % cols) * W + W, (i // cols) * H + H))
                  for i in range(len(spec))]

    gif = OUT / f"{name}.gif"
    frames[0].save(gif, save_all=True, append_images=frames[1:],
                   duration=[ms for _, ms in spec], loop=0, optimize=True, disposal=2)
    return gif, len(frames), sum(ms for _, ms in spec)


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    for fname, fn in PAGES:
        (OUT / fname).write_text(fn().render())
        print("wrote", fname)
    if "--gif" in sys.argv:
        for name, frames_fn in MOTION.items():
            g, k, total = build_gif(name, frames_fn)
            print(f"wrote {g.name}  {k} frames, {total/1000:.1f}s cycle, "
                  f"{g.stat().st_size//1024} KB")
