#!/usr/bin/env python3
"""Flattens this folder's dripper SVGs into Android VectorDrawables.

    python3 convert_drippers.py            # writes ../../v1/app/src/main/res/drawable/
    python3 convert_drippers.py --check     # exit 1 if any XML is out of date

`generate.py` draws the icons; this is the other half of that pipeline. It was
referenced by `Illustrations.kt`'s docstring from the day the vectors were first
added and had never actually been kept, so the fifteen `ic_dripper_*.xml` were
hand-flattened once and then diverged from the SVGs the moment either changed.
Written for real on 2026-08-22, when the whole set was redrawn.

THE CONVERSION IS DELIBERATELY DUMB, and that is what makes it trustworthy:
VectorDrawable's `pathData` is SVG path syntax, so a `<path>` is copied
verbatim, and the only real work is turning `<ellipse>`/`<circle>` -- which
VectorDrawable has no element for -- into the two-arc path every vector icon
uses for a closed round shape. Nothing is scaled, re-ordered or optimised, so a
diff between an SVG and its XML is readable by eye.

Stroke colour, caps and joins come from the SVG's one wrapping `<g>`; the
per-shape `stroke-width` is the only attribute that varies, exactly as
`generate.py` writes it. `viewportWidth/Height` follow the SVG's 100x100 box,
and the 26dp intrinsic size is the glyph size `-1.1`'s rows draw at -- callers
size these explicitly (see `DripperGlyph`), so it is a default, not a constraint.
"""
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

HERE = pathlib.Path(__file__).resolve().parent
DRAWABLE = HERE.parent.parent / "v1" / "app" / "src" / "main" / "res" / "drawable"
SVG = "{http://www.w3.org/2000/svg}"

HEAD = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by plan/dripper_icons/convert_drippers.py from {src}.
  Do not hand-edit: change the drawing in generate.py, re-run both, and the
  diff here should be exactly the shape you changed. White linework only;
  callers draw the BRAND disc (see ui/components/Illustrations.kt).
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="26dp"
    android:height="26dp"
    android:viewportWidth="100"
    android:viewportHeight="100">
"""

PATH = """    <path
        android:pathData="{d}"
        android:strokeColor="{color}"
        android:strokeWidth="{sw}"
        android:fillColor="#00000000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />
"""


def _num(s):
    """1.0 -> "1", 2.60 -> "2.6" -- keeps the XML as short as the SVG's own."""
    f = float(s)
    return f"{f:g}"


def _ellipse_path(cx, cy, rx, ry):
    """The two-arc form: start at the left extreme, sweep right, sweep back.
    VectorDrawable has no ellipse element, and a single arc cannot close a
    full turn (start == end is a no-op), which is why every icon set does it
    in two halves."""
    cx, cy, rx, ry = (float(v) for v in (cx, cy, rx, ry))
    return (f"M{cx - rx:g},{cy:g} A{rx:g},{ry:g} 0 1,0 {cx + rx:g},{cy:g} "
            f"A{rx:g},{ry:g} 0 1,0 {cx - rx:g},{cy:g}")


def convert(svg_path):
    root = ET.parse(svg_path).getroot()
    group = root.find(f"{SVG}g")
    color = group.get("stroke", "#FFFFFF")
    body = ""
    for el in group:
        tag = el.tag.replace(SVG, "")
        sw = _num(el.get("stroke-width", "1"))
        if tag == "path":
            d = re.sub(r"\s+", " ", el.get("d").strip())
        elif tag == "ellipse":
            d = _ellipse_path(el.get("cx"), el.get("cy"), el.get("rx"), el.get("ry"))
        elif tag == "circle":
            r = el.get("r")
            d = _ellipse_path(el.get("cx"), el.get("cy"), r, r)
        else:
            raise SystemExit(f"{svg_path.name}: unhandled <{tag}> -- teach this "
                             f"script the element rather than hand-editing the XML")
        body += PATH.format(d=d, color=color, sw=sw)
    return HEAD.format(src=f"plan/dripper_icons/{svg_path.name}") + body + "</vector>\n"


def main():
    check = "--check" in sys.argv
    stale, written = [], 0
    for svg in sorted(HERE.glob("*.svg")):
        if svg.stem.startswith("_"):        # the QA sheet, not an icon
            continue
        # hario-v60.svg -> ic_dripper_hario_v60.xml, the names DRIPPER_ICONS
        # in Illustrations.kt maps Choices.DRIPPERS onto.
        out = DRAWABLE / f"ic_dripper_{svg.stem.replace('-', '_')}.xml"
        xml = convert(svg)
        if out.exists() and out.read_text() == xml:
            continue
        if check:
            stale.append(out.name)
        else:
            out.write_text(xml)
            written += 1
    if check:
        print("\n".join(stale) or "up to date")
        sys.exit(1 if stale else 0)
    print(f"wrote {written} vector drawable(s) -> {DRAWABLE}")


if __name__ == "__main__":
    main()
